# Generated by Django 4.2.7 on 2026-02-11 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('is_cracked', models.BooleanField()),
                ('cnn_accuracy', models.FloatField()),
                ('cnn_confidence', models.FloatField()),
                ('resnet_accuracy', models.FloatField()),
                ('resnet_confidence', models.FloatField()),
                ('xception_accuracy', models.FloatField()),
                ('xception_confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detections',
                'ordering': ['-created_at'],
            },
        ),
    ]
